openapi: 3.0.0
info:
  title: Flask Terraform API
  description: API to manage Terraform infrastructure for EC2 and OpenStack
  version: 1.0.0

paths:
  /terraform/ec2:
    post:
      summary: Launch an EC2 instance using Terraform
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ami_id:
                  type: string
                  description: The AMI ID for the EC2 instance
                instance_type:
                  type: string
                  description: The EC2 instance type
                  default: "p3.2xlarge"
                vpc_id:
                  type: string
                  description: The VPC ID where the EC2 instance will be deployed
                subnet_id:
                  type: string
                  description: The subnet ID where the EC2 instance will be deployed
                key_name:
                  type: string
                  description: The key pair name for SSH access
                iam_instance_profile:
                  type: string
                  description: The IAM instance profile for permissions
                ansible_s3_bucket:
                  type: string
                  description: The S3 bucket containing the Ansible playbook
                ansible_playbook:
                  type: string
                  description: The Ansible playbook filename
      responses:
        '200':
          description: EC2 Instance launched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: EC2 Instance launched
                  public_ip:
                    type: string
                  vpc_id:
                    type: string
                  subnet_id:
                    type: string
        '400':
          description: Invalid JSON data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Error occurred during Terraform execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /terraform/openstack:
    post:
      summary: Launch an OpenStack instance using Terraform
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image_id:
                  type: string
                  description: The OpenStack image ID for the instance
                flavor_id:
                  type: string
                  description: The flavor ID for the OpenStack instance
                network_id:
                  type: string
                  description: The network ID where the OpenStack instance will be deployed
                key_name:
                  type: string
                  description: The key pair name for SSH access
                security_group:
                  type: string
                  description: The security group ID for the OpenStack instance
                region:
                  type: string
                  description: The OpenStack region where the instance will be deployed
      responses:
        '200':
          description: OpenStack Instance launched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: OpenStack Instance launched
                  public_ip:
                    type: string
                  vpc_id:
                    type: string
                  subnet_id:
                    type: string
        '400':
          description: Invalid JSON data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Error occurred during Terraform execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /terraform/status:
    get:
      summary: Get instance status
      responses:
        '200':
          description: Instance details
          content:
            application/json:
              schema:
                type: object
                properties:
                  public_ip:
                    type: string
                  vpc_id:
                    type: string
                  subnet_id:
                    type: string
        '404':
          description: No instance deployed yet

  /launch:
    get:
      summary: Launch instance in browser
      responses:
        '302':
          description: Redirect to the launched instance
          headers:
            Location:
              description: URL of the instance
              schema:
                type: string
                example: "http://<public_ip>:8080"
