---
- name: Install PyTorch on EC2
  hosts: localhost
  become: yes
  tasks:
    - name: Install Python3 and pip
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install PyTorch with CUDA support
      pip:
        name:
          - torch
          - torchvision
          - torchaudio
        extra_args: "--index-url https://download.pytorch.org/whl/cu121"
