openapi: 3.0.0
info:
  title: Flask Terraform API
  description: API to manage Terraform infrastructure
  version: 1.0.0

paths:
  /terraform:
    post:
      summary: Launch an instance using Terraform
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Instance launched
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  public_ip:
                    type: string
                  vpc_id:
                    type: string
                  subnet_id:
                    type: string
  /terraform/status:
    get:
      summary: Get instance status
      responses:
        '200':
          description: Instance details
          content:
            application/json:
              schema:
                type: object
                properties:
                  public_ip:
                    type: string
                  vpc_id:
                    type: string
                  subnet_id:
                    type: string
  /launch:
    get:
      summary: Launch instance in browser
      responses:
        '302':
          description: Redirect to the launched instance
